(defpackage :ltk-plotchart
  (:use :cl :ltk)
  (:nicknames :chart)
  (:export
    ; classes 
    :bar-chart
    :box-plot
    :gantt-chart
    :histogram
    :horizontal-bar-chart
    :isometric-plot
    :logx-logy-plot
    :logx-y-plot
    :pie-chart
    :polar-plot
    :radial-chart
    :right-axis
    :spiral-pie
    :status-timeline
    :strip-chart
    :table-chart
    :ternary-diagram
    :threed-bar-chart
    :threed-plot
    :threed-ribbon-chart
    :threed-ribbon-plot
    :time-chart
    :tx-plot
    :windrose
    :xy-plot
    :x-logy-plot
    ; create-X functions
    :create-bar-chart
    :create-box-plot
    :create-gantt-chart
    :create-histogram
    :create-horizontal-bar-chart
    :create-isometric-plot
    :create-logx-logy-plot
    :create-logx-y-plot
    :create-pie-chart
    :create-polar-plot
    :create-radial-chart
    :create-right-axis
    :create-spiral-pie
    :create-status-timeline
    :create-strip-chart
    :create-3d-bar-chart
    :create-3d-plot
    :create-3d-ribbon-chart
    :create-3d-ribbon-plot
    :create-table-chart
    :create-ternary-diagram
    :create-time-chart
    :create-tx-plot
    :create-windrose
    :create-xy-plot
    :create-x-logy-plot
    ; remaining functions
    :add-milestone
    :add-period
    :background
    :balloon
    :balloon-config
    :cell-configure
    :color 
    :colors
    :color-map
    :colour
    :colours
    :colour-map
    :config
    :connect
    :corner-text
    :data-config
    :dot-config
    :draw-area
    :draw-box-and-whiskers
    :draw-circle
    :draw-contour-lines
    :draw-contour-lines-function-values
    :draw-dot
    :draw-filled-circle
    :draw-filled-polygon
    :draw-filled-rectangle
    :draw-grid
    :draw-interval
    :draw-label-dot
    :draw-line
    :draw-minmax
    :draw-rectangle
    :draw-region
    :draw-ticklines
    :draw-trendline
    :draw-vector
    :draw-vertical-line
    :draw-x-band
    :draw-y-band
    :explode
    :font
    :gridsize
    :horizontal-scrollbar
    :interpolate-data
    :legend
    :legend-config
    :legend-isometric-lines
    :legend-remove
    :legend-shades
    :milestone
    :period
    :plaintext
    :plaintext-config
    :plot
    :plot-cumulative
    :plot-data
    :plot-list
    :plot-pack
    :rchart
    :ribbon
    :row
    :save-plot
    :separator
    :subtitle
    :summary
    :task
    :title-text
    :v-subtext
    :v-text
    :vector-config
    :vertical-scrollbar
    :x-config
    :x-subtext
    :x-text
    :x-ticklines
    :y-config
    :y-subtext
    :y-text
    :y-ticklines
    ))
